version: '3'
services:

    thor_db:
        container_name: postgres-$JOB_NAME
        image: postgres
        environment:
        - POSTGRES_PASSWORD=thor
        - POSTGRES_USER=thor
        - POSTGRES_DB=thor
        volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-$JOB_NAME        
        build: ./nginx
        restart: always
        expose:
        - "80"
        volumes:        
        - api_data:/docker_api        
        - ./log:/var/log/nginx              
        depends_on:
        - api
        
    api:
        container_name: api-$JOB_NAME
        build: ./api        
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini         
        ports:
        - "8002:8000"
        volumes:
        - api_data:/docker_api        
        depends_on:
        - thor_db
        environment:
        - DATABASE_URL=postgres://thor:thor@thor_db/thor

volumes:
    api_data:
    pgdata:

