version: '3'
services:

    thor_db:
        container_name: $JOB_NAME-postgres
        image: postgres
        environment:
        - POSTGRES_PASSWORD=thor
        - POSTGRES_USER=thor
        - POSTGRES_DB=thor
        volumes:
        - pgdata:/var/lib/postgresql/data/
        networks:
        - $JOB_NAME_db_network

    nginx:
        container_name: $JOB_NAME-nginx        
        build: ./nginx
        restart: always
        expose:
        - "80"
        volumes:        
        - api_data:/docker_api        
        - ./log:/var/log/nginx              
        depends_on:
        - api
        networks:
        - $JOB_NAME_nginx_network
        
    api:
        container_name: $JOB_NAME-api
        build: ./api        
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini
        expose:
        - "8000"
        volumes:
        - api_data:/docker_api        
        depends_on:
        - thor_db
        environment:
        - DATABASE_URL=postgres://thor:thor@thor_db/thor
        networks:
        - $JOB_NAME_nginx_network
        - $JOB_NAME_db_network

networks:
  $JOB_NAME_nginx_network:
    driver: bridge
  $JOB_NAME_db_network:
    driver: bridge

volumes:
    api_data:
    pgdata:

